### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by valkyrienyanko** [WilfordBrimley/discord2twitch2discord#1]
I see many things to improve your bot with.
- Nodemon auto restarts your bot whenever you make and save changes to files speeding up development.
- ESLint enforces a standard code style.
- You should only use client.on('message') once, using it more then once will cause unnecessary overhead
- dotenv will hide your token in a `.env` file which you would add to `.gitignore`

Let me know if you want this and I'll create a PR when I have time.

**Comment by WilfordBrimley** [comment]
Sure if you'd like. Remember there's two clients here. I've edited to make that more clear as to why there needs to be 2 on.message listeners.

**Comment by valkyrienyanko** [comment]
Oh sorry I didn't look close enough to see that.

**Comment by WilfordBrimley** [comment]
Totally fine!

**Comment by valkyrienyanko** [comment]
Done. See #2
